routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['web', 'auth'])->group(function () {
    Route::resource('categories', 'CategoriesController');
    Route::resource('transactions', 'TransactionsController');
});

Route::prefix('admin')->middleware(['web', 'auth', 'admin'])->group(function () {
    Route::get('/', function(){
        return view('admin.index');
    })->name('dashboard');

    Route::get('users', 'Admin\UsersController@index')->name('users');
});

app/Http/Controllers/TransactionsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Transaction;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;

class TransactionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transactions = Transaction::with('category')->User()->paginate(10);

        return view('transactions.index', compact('transactions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Cache::remember('categories', 600, function () {
            return Category::User()->select('id', 'name')->get();
        });

        return view('transactions.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'amount' => 'required|numeric|between:-999999,999999',
            'category_id' => 'required',
            'note' => 'required',
        ]);

        $cat_check = Category::where(['id' => $request->category_id, 'user_id' => Auth()->user()->id])->first();
        if(!$cat_check){
            return back()->with('error', 'Please select a valida category');
        }
        $tran = DB::transaction(function() use($request){
            try{
                $tran = new Transaction();
                $tran->amount = $request->amount;
                $tran->category_id = $request->category_id;
                $tran->note = $request->note;
                $tran->user_id = Auth()->user()->id;
                $tran->wallet_balance = Auth()->user()->wallet;
                $tran->save();
        
                Auth()->user()->wallet += $request->amount;
                Auth()->user()->save();
    
                return true;
            } catch(\Exception $e){
                return false;
            }
        });
        if($tran){
            return back()->with('success', 'Added successfully!');
        }
        return back()->with('error', 'Something went wrong!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/transactions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Add a transaction</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('transactions.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Category</label>

                            <div class="col-md-6">
                                <select name="category_id" class="form-control @error('category_id') is-invalid @enderror" required>
                                    <option selected hidden disabled>Please select a category</option>
                                    @foreach($categories as $cat)
                                    <option value="{{$cat->id}}" {{old('category_id') == $cat->id ? 'selected' : ''}}> {{$cat->name}} </option>
                                    @endforeach
                                </select>
                                @error('category_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="amount" class="col-md-4 col-form-label text-md-right">Amount</label>

                            <div class="col-md-6">
                                <input id="amount" type="number" step="0.00" class="form-control @error('amount') is-invalid @enderror" name="amount" value="{{ old('amount') }}" required autocomplete="name" autofocus>

                                @error('amount')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="note" class="col-md-4 col-form-label text-md-right">Note</label>

                            <div class="col-md-6">
                                <textarea name="note" class="form-control @error('note') is-invalid @enderror"></textarea>
                                @error('note')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Add
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/transactions/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="text-right">
                <a href="{{route('transactions.create')}}" class="btn btn-primary">
                    Add a transaction
                </a>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Category</th>
                <th scope="col">Amount</th>
                <th scope="col">Note</th>
                <th scope="col">Wallet balance before</th>
              </tr>
            </thead>
            <tbody>
              @php
                  $total_income = 0;
                  $total_expenses = 0;
              @endphp
                @foreach($transactions as $trans)
              <tr>
                <th scope="row">{{ $trans->id }}</th>
                <td>{{ $trans->category->name }}</td>
                <td>{{ $trans->amount }}</td>
                <td>{{ $trans->note }}</td>
                <td>{{ $trans->wallet_balance }}</td>
              </tr>
              @php
              if($trans->amount > 0)
                  $total_income += $trans->amount;
              else
                  $total_expenses += $trans->amount;
              @endphp
              @endforeach
            </tbody>
            <tfoot>
              <tr>
              <td></td>
              <td></td>
                <td>Total Income: {{$total_income}}</td>
                <td>Total expenses: {{$total_expenses}}</td>
                <td>Wallet: {{Auth()->user()->wallet}}</td>
              </tr>
            </tfoot>
          </table>
          {{ $transactions->links() }}
    </div>
</div>
@endsection