routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['web', 'auth'])->group(function () {
    Route::resource('categories', 'CategoriesController');
    Route::resource('transactions', 'TransactionsController');
});

Route::prefix('admin')->middleware(['web', 'auth', 'admin'])->group(function () {
    Route::get('/', function(){
        return view('admin.index');
    })->name('dashboard');

    Route::get('users', 'Admin\UsersController@index')->name('users');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar', 'birthdate', 'phone',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function expenses(){
        return $this->hasMany(Transaction::class)->where('amount', '<', 0);
    }

    public function income(){
        return $this->hasMany(Transaction::class)->where('amount', '>', 0);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::withCount([
            'expenses' => function ($query) {
                        $query->select(DB::raw("SUM(amount) as expenses"))->where('amount', '<', 0);
                    },
                    'income' => function ($query) {
                        $query->select(DB::raw("SUM(amount) as income"))->where('amount', '>', 0);
                    }
                ])->paginate(10);

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/users/index.blade.php
@extends('layouts.layout.layout')

@section('head')
<title>Users</title>
<style>
	.search-box {
		position: absolute;
		left: 0;
		top: 50px;
		left: 15px;
		z-index: 250;
		border-radius: 2px;
		border: 1px solid #aaa;
		padding: 5px;
		display: none;
	}
	.custom-search-select.show + .search-box {
		display: block;
	}
	.custom-search-select .dropdown-menu {
		padding-top: 50px;
	}
	.custom-search-select .inner {
		max-height: 140px!important;
	}
</style>
@endsection

@section('body-header')

@endsection

@section('body')
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="kt-portlet kt-portlet--mobile">
        <form action="#" method="POST">
            <div class="kt-portlet__body kt-portlet__body--fit">
                <div class="kt-datatable kt-datatable--default kt-datatable--brand kt-datatable--loaded" id="kt_apps_user_list_datatable" style="">
                    <table class="kt-datatable__table" style="display: block;">
                        <thead class="kt-datatable__head">
                            <tr class="kt-datatable__row" style="left: 0px;">
                                <th class="kt-datatable__cell"><span style="width: 100px;">ID</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Name</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Email</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Birthdate</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Phone</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Wallet</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Total expenses</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Total Income</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Date created</span></th>
                            </tr>
                        </thead>
                        <tbody style="" class="kt-datatable__body">
                            @foreach($users as $key=>$user)
                            <tr data-row="{{$user->id}}" class="kt-datatable__row">
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$user->id}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$user->name}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$user->email}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$user->birthdate}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$user->phone}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$user->wallet}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$user->expenses_count}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$user->income_count}}</span>
                                </td>
                                <td data-field="Type" data-autohide-disabled="false" class="kt-datatable__cell">
                                    <span style="width: 100px;">{{$user->created_at->format('d/m/Y')}}</span>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="kt-pagination kt-pagination--brand">
                {{$users->links()}}
            </div>
        </form>
    </div>
</div>
@endsection

@section('scripts')
@endsection